---
# ====== Application: Vanilla WIP Form =======================
id: 150
identification: 
  name: Vanilla WIP Form
  alias: WIP
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: N

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: No Authentication # 309047159332781536

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Allow
  referrer-policy: strict-origin-when-cross-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_FRONGPMSTDEV

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:2:&SESSION.'
    page: 2 # GPMS Narrative Billing

  login-url: 
    url: 'f?p=&APP_ID.:2:&SESSION.'
    page: 2 # GPMS Narrative Billing

navigation-menu: 
  list-template: Top Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top

navigation-bar: 
  implementation: Classic

javascript: 
  file-urls: 
  - '#APP_FILES#typo#MIN#.js'
  - '#APP_FILES#PreBillingAdjustments#MIN#.js'
  - 'https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.all.min.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_IMAGES#app-icon.css?version=#APP_VERSION#'
  - '#APP_FILES#PreBillingAdjustments#MIN#.css'
  - 'https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.min.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 13984863123593696
  identification: 
    name: APP_NAME

  value: 
    static-value: Pre-Billing Adjustments

- # ====== Substitution: CLIENT ================================
  id: 13984863123593695
  identification: 
    name: CLIENT

  value: 
    static-value: DEV

- # ====== Substitution: ENV ===================================
  id: 13984863123593694
  identification: 
    name: ENV

  value: 
    static-value: DEV

- # ====== Substitution: CURRENCY_FORMAT =======================
  id: 13984863123593693
  identification: 
    name: CURRENCY_FORMAT

  value: 
    static-value: 99,99,99,999.99

component-settings: 
- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 1388351601195859
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 41016584461815

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 1416659539264107
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 41740436598265

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 1417348938264108
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 41740436598296

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 1418005976264108
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 41740436598325

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 28685707353028812
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 29369873816057961
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 42424679425718232
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 290007665901426309
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 308351914057310781
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 308352196303310781
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 308352775324310782
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_IR ========================
  id: 308353335452310782
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 308353641747310782
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 1

