create table wksp_frongpmstdev.axgpms_expenses (
    project_number varchar2(100 byte),
    expense_type   varchar2(100 byte),
    raw_cost       number(2, 10),
    session_id     number,
    status         varchar2(100 byte),
    expense_cost   number(10, 2)
);


-- sqlcl_snapshot {"hash":"7e51934481da706b51c7361f0a23e66595cbfbc7","type":"TABLE","name":"AXGPMS_EXPENSES","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>AXGPMS_EXPENSES</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>PROJECT_NUMBER</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>EXPENSE_TYPE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>RAW_COST</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>2</PRECISION><SCALE>10</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SESSION_ID</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STATUS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>EXPENSE_COST</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>10</PRECISION><SCALE>2</SCALE></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}