create table wksp_frongpmstdev.axxml_tab (
    id         number,
    xml_data   xmltype,
    vc2_data   varchar2(32000 byte),
    xml_clob   clob,
    session_id number,
    seq        number
        generated always as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder nocycle
        nokeep noscale
    not null enable,
    ts         timestamp(6) default systimestamp
);


-- sqlcl_snapshot {"hash":"24bc8080772a1fc8492930cf5baa439b71f130ef","type":"TABLE","name":"AXXML_TAB","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>AXXML_TAB</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>XML_DATA</NAME><DATATYPE>XMLTYPE</DATATYPE><TYPE_PROPERTIES><SCHEMA>PUBLIC</SCHEMA><NAME>XMLTYPE</NAME></TYPE_PROPERTIES></COL_LIST_ITEM><COL_LIST_ITEM><NAME>VC2_DATA</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>XML_CLOB</NAME><DATATYPE>CLOB</DATATYPE><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SESSION_ID</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SEQ</NAME><DATATYPE>NUMBER</DATATYPE><IDENTITY_COLUMN><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><GENERATION>ALWAYS</GENERATION><START_WITH>3720044</START_WITH><INCREMENT>1</INCREMENT><MINVALUE>1</MINVALUE><MAXVALUE>9999999999999999999999999999</MAXVALUE><CACHE>20</CACHE></IDENTITY_COLUMN><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TS</NAME><DATATYPE>TIMESTAMP</DATATYPE><SCALE>6</SCALE><DEFAULT>SYSTIMESTAMP</DEFAULT></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES><TABLE_PROPERTIES><COLUMN_PROPERTIES><COL_LIST><COL_LIST_ITEM><NAME>XML_DATA</NAME><DATATYPE>XMLTYPE</DATATYPE><XMLTYPE_PROPERTIES><XMLTYPE_STORAGE><STORE_AS>BINARY_XML</STORE_AS><LOB_PROPERTIES><STORAGE_TABLE></STORAGE_TABLE></LOB_PROPERTIES></XMLTYPE_STORAGE></XMLTYPE_PROPERTIES></COL_LIST_ITEM><COL_LIST_ITEM><NAME>XML_CLOB</NAME><DATATYPE>CLOB</DATATYPE><LOB_PROPERTIES><STORAGE_TABLE></STORAGE_TABLE></LOB_PROPERTIES></COL_LIST_ITEM></COL_LIST></COLUMN_PROPERTIES></TABLE_PROPERTIES></RELATIONAL_TABLE></TABLE>"}