create table wksp_frongpmstdev.load_narratives_err$ (
    ora_err_number$       number,
    ora_err_mesg$         varchar2(2000 byte),
    ora_err_rowid$        urowid(4000),
    ora_err_optyp$        varchar2(2 byte),
    ora_err_tag$          varchar2(2000 byte),
    id                    varchar2(4000 byte),
    expenditure_item_id   varchar2(4000 byte),
    invoice_narrative     varchar2(32767 byte),
    internal_comments     varchar2(32767 byte),
    expenditure_item_date varchar2(4000 byte),
    person_name           varchar2(32767 byte),
    title                 varchar2(32767 byte),
    quantity              varchar2(4000 byte),
    uom                   varchar2(32767 byte),
    billable              varchar2(32767 byte),
    standard_rate         varchar2(4000 byte),
    standard_amount       varchar2(4000 byte),
    agreement_rate        varchar2(4000 byte),
    agreement_amount      varchar2(4000 byte),
    real__rate            varchar2(4000 byte),
    fee_allocation        varchar2(4000 byte),
    billable_hold         varchar2(32767 byte),
    currency              varchar2(32767 byte),
    description           varchar2(32767 byte),
    inv_status            varchar2(32767 byte),
    draft_status          varchar2(32767 byte),
    draft_invoice_number  varchar2(32767 byte)
);


-- sqlcl_snapshot {"hash":"1d4f5e910cfcb85f6676dfdc7c2ba301271d34ad","type":"TABLE","name":"LOAD_NARRATIVES_ERR$","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>LOAD_NARRATIVES_ERR$</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>ORA_ERR_NUMBER$</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ORA_ERR_MESG$</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ORA_ERR_ROWID$</NAME><DATATYPE>UROWID</DATATYPE><LENGTH>4000</LENGTH></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ORA_ERR_OPTYP$</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ORA_ERR_TAG$</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ID</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>EXPENDITURE_ITEM_ID</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INVOICE_NARRATIVE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INTERNAL_COMMENTS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>EXPENDITURE_ITEM_DATE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>PERSON_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TITLE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>QUANTITY</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>UOM</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>BILLABLE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STANDARD_RATE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STANDARD_AMOUNT</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>AGREEMENT_RATE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>AGREEMENT_AMOUNT</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>REAL__RATE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>FEE_ALLOCATION</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>BILLABLE_HOLD</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>CURRENCY</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>DESCRIPTION</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INV_STATUS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>DRAFT_STATUS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>DRAFT_INVOICE_NUMBER</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>32767</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}