create table wksp_frongpmstdev.ma_approval_invoices (
    taskid                varchar2(4000 byte),
    tasknumber            varchar2(1000 byte),
    task_definition_name  varchar2(4000 byte),
    priority              number,
    title                 varchar2(4000 byte),
    identification_key    number,
    contract_number       varchar2(1000 byte),
    invoice_num           number,
    invoice_status_code   varchar2(1000 byte),
    assignee              varchar2(2000 byte),
    assignee_display_name varchar2(2000 byte),
    invoice_currency_code varchar2(100 byte),
    invoice_date          varchar2(1000 byte),
    invoice_amount        number,
    write_off_amount      number,
    bill_customer_name    varchar2(1000 byte),
    bill_cust_acct_num    varchar2(1000 byte),
    bill_cust_acct_name   varchar2(1000 byte),
    bill_cust_site        varchar2(1000 byte)
);


-- sqlcl_snapshot {"hash":"8e6c120e0b821aed740de198284d369abbaf0b6a","type":"TABLE","name":"MA_APPROVAL_INVOICES","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>MA_APPROVAL_INVOICES</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>TASKID</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TASKNUMBER</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TASK_DEFINITION_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>PRIORITY</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>TITLE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>IDENTIFICATION_KEY</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>CONTRACT_NUMBER</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INVOICE_NUM</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INVOICE_STATUS_CODE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ASSIGNEE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ASSIGNEE_DISPLAY_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INVOICE_CURRENCY_CODE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INVOICE_DATE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>INVOICE_AMOUNT</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>WRITE_OFF_AMOUNT</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>BILL_CUSTOMER_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>BILL_CUST_ACCT_NUM</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>BILL_CUST_ACCT_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>BILL_CUST_SITE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}