create table wksp_frongpmstdev.progress_entries (
    percentage   number,
    message      varchar2(100 byte),
    created_date timestamp(6),
    user_email   varchar2(100 byte)
);


-- sqlcl_snapshot {"hash":"6d4b146b8005aeb9f91d86082e6155d10b4a4057","type":"TABLE","name":"PROGRESS_ENTRIES","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>PROGRESS_ENTRIES</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>PERCENTAGE</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>MESSAGE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>CREATED_DATE</NAME><DATATYPE>TIMESTAMP</DATATYPE><SCALE>6</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>USER_EMAIL</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}