create table wksp_frongpmstdev.spell_checker_dtl (
    id              number
        generated always as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder nocycle
        nokeep noscale
    not null enable,
    narrative       varchar2(4000 byte),
    error_word      varchar2(4000 byte),
    suggested_words varchar2(4000 byte),
    exp_item_id     number,
    user_email      varchar2(100 byte)
);

alter table wksp_frongpmstdev.spell_checker_dtl
    add constraint spell_checker_dtl_pk primary key ( id )
        using index enable;


-- sqlcl_snapshot {"hash":"490083c1dea44f936576f4f1d96dd38f19c668f7","type":"TABLE","name":"SPELL_CHECKER_DTL","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>SPELL_CHECKER_DTL</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME><DATATYPE>NUMBER</DATATYPE><IDENTITY_COLUMN><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><GENERATION>ALWAYS</GENERATION><START_WITH>141</START_WITH><INCREMENT>1</INCREMENT><MINVALUE>1</MINVALUE><MAXVALUE>9999999999999999999999999999</MAXVALUE><CACHE>20</CACHE></IDENTITY_COLUMN><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>NARRATIVE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>ERROR_WORD</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SUGGESTED_WORDS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>4000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>EXP_ITEM_ID</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>USER_EMAIL</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>SPELL_CHECKER_DTL_PK</NAME><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}