create table wksp_frongpmstdev.xxgpms_lookup (
    id           number
        generated always as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder nocycle
        nokeep noscale
    not null enable,
    lookup_type  varchar2(2000 char),
    lookup_value varchar2(2000 char),
    status       varchar2(10 char)
);

alter table wksp_frongpmstdev.xxgpms_lookup
    add constraint xxgpms_lookup_id_pk primary key ( id )
        using index enable;


-- sqlcl_snapshot {"hash":"7376895d800c1aeae05aa8173594fa24d16c284e","type":"TABLE","name":"XXGPMS_LOOKUP","schemaName":"WKSP_FRONGPMSTDEV","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><NAME>XXGPMS_LOOKUP</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME><DATATYPE>NUMBER</DATATYPE><IDENTITY_COLUMN><SCHEMA>WKSP_FRONGPMSTDEV</SCHEMA><GENERATION>ALWAYS</GENERATION><START_WITH>21</START_WITH><INCREMENT>1</INCREMENT><MINVALUE>1</MINVALUE><MAXVALUE>9999999999999999999999999999</MAXVALUE><CACHE>20</CACHE></IDENTITY_COLUMN><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LOOKUP_TYPE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2000</LENGTH><CHAR_SEMANTICS></CHAR_SEMANTICS><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LOOKUP_VALUE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>2000</LENGTH><CHAR_SEMANTICS></CHAR_SEMANTICS><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STATUS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>10</LENGTH><CHAR_SEMANTICS></CHAR_SEMANTICS><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>XXGPMS_LOOKUP_ID_PK</NAME><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}